### ISSUE TITLE
C# - Exception when diffing long files (Invalid URI: The Uri string is too long.)

### ISSUE THREAD

**Issue by XXLuigiMario** [google/diff-match-patch#22] opened 2018-07-11 11:11 UTC
I'm trying to diff several files sometimes up to around half a megabyte in size and with some of them I get a "Invalid URI: The Uri string is too long." exception. This is using the patch_make function.

**Comment by NeilFraser** [comment] 2018-07-11 20:29
Confirmed, it blows up somewhere between 40kb and 80kb (likely 64kb):
```
Unhandled Exception:
System.UriFormatException: Invalid URI: The Uri string is too long.
  at System.UriHelper.EscapeString (System.String input, System.Int32 start, System.Int32 end, System.Char[] dest, System.Int32& destPos, System.Boolean isUriString, System.Char force1, System.Char force2, System.Char rsvd) [0x00019] in <a24e193d5cf14a42ac00ebaea26ec7bc>:0 
  at System.Uri.EscapeDataString (System.String stringToEscape) [0x00026] in <a24e193d5cf14a42ac00ebaea26ec7bc>:0 
  at DiffMatchPatch.diff_match_patch.diff_toDelta (System.Collections.Generic.List`1[T] diffs) [0x00045] in <e4f34ccfe2314686801ad2a4e0967a91>:0 
```

That's utterly ridiculous.  A string utility should not have a size limit.  Last time I saw behaviour like this was when I was using Visual Basic 3.  Figures, those are both Microsoft languages.

Working on a fix...

**Comment by NeilFraser** [comment] 2018-07-11 23:13
Fixed in d9b6d3357e800f23949075499554ecefe630c82d.
Thanks for reporting this bug.  I can't believe it's 2018 and we still have to deal with hard-coded string limits.

Will follow up with a commit shortly that adds the new test case to the other languages.

**Closed by NeilFraser** 2018-07-11 23:13 UTC

**Comment by NeilFraser** [comment] 2018-07-12 00:54
Well this is interesting.  Tests (using Mono) shows the overflow cutoff is exactly at 64kb, but the documentation from Microsoft claims that the overflow cutoff is exactly at 32kb.
https://msdn.microsoft.com/en-us/library/system.uri.escapedatastring(v=vs.110).aspx

@XXLuigiMario If you are using Microsoft's version of C#, could you run the unit tests and see if it succeeds?  If so, then Microsoft's documentation is wrong.  If not, then Mono's implementation is different and I need to reduce the overflow constant to be the lowest common denominator.

**Comment by XXLuigiMario** [comment] 2018-07-12 08:45
I've been digging a little bit and what I found seems to confirm that Microsoft's documentation is wrong.

![documentation](https://user-images.githubusercontent.com/7153662/42622151-05552a5a-85c0-11e8-87f0-fec27e61057a.png)

I'm not sure if perhaps the limit used to be lower with an earlier version of .NET Framework as some other answers pointed out [in the same question](https://stackoverflow.com/questions/6695208/uri-escapedatastring-invalid-uri-the-uri-string-is-too-long) but the tests passed both when setting the target platform to .NET Framework 4.6.1 and .NET Framework 4.

**Comment by NeilFraser** [comment] 2018-07-12 18:49
@XXLuigiMario Thanks for checking .NET's behaviour.  Since it matches what I see, I'll leave the limit at 64k for now, but reduce it to 32k if we ever get a complaint.
